variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    REPOSITORY_HOST: "gitlab.shopware.com:5005"
    PLATFORM_BRANCH: "6.1"

stages:
    - Build
    - Static analysis
    - Unit

cache:
    key: "Eternal static key"
    paths:
        - .composer

Build-Analysis-Container:
    stage: Build
    only:
        refs:
            - master
        changes:
            - dev-ops/container/static-analysis/*
            - dev-ops/container/static-analysis/**/*
    image: docker
    services:
        -   name: docker:18.09.7-dind
            alias: docker
    script:
        - export IMAGE_NAME="${REPOSITORY_HOST}/shopware/shopware-cloud/connect/php-static-analysis"
        - apk add git bash
        - docker login gitlab.shopware.com:5005 -u $REGISTRY_USERNAME --password-stdin < $REGISTRY_PASSWORD_FILE
        - docker build dev-ops/container/static-analysis -t "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
        - docker tag "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_NAME}:latest"
        - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
        - docker push "${IMAGE_NAME}:latest"

Cs-Fixer:
    stage: Static analysis
    image: gitlab.shopware.com:5005/shopware/shopware-cloud/connect/php-static-analysis:latest
    script:
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - php-cs-fixer fix --dry-run -v --allow-risky=yes --format=junit src | tee php-cs-fixer.xml
    artifacts:
        reports:
            junit: php-cs-fixer.xml


Psalm:
    stage: Static analysis
    image: gitlab.shopware.com:5005/shopware/shopware-cloud/connect/php-static-analysis:latest
    script:
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - psalm --output-format=compact


Phpstan:
    stage: Static analysis
    image: gitlab.shopware.com:5005/shopware/shopware-cloud/connect/php-static-analysis:latest
    script:
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - phpstan analyze --configuration phpstan.neon src
Unit:
    stage: Unit
    image: shopware/development:latest
    services:
        -   name: mysql:5.7
            alias: mysql
        -   name: elastic/elasticsearch:7.1.1
            alias: elasticsearch
            command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
    before_script:
        - zip -rq plugin.zip .
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git --branch $PLATFORM_BRANCH
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform --branch $PLATFORM_BRANCH
        - unzip -q plugin.zip -d development/custom/plugins/SaasConnect
        - cd development
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SaasConnect
        - composer dump-autoload -d custom/plugins/SaasConnect
        - ./psh.phar init-test-databases
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SaasConnect/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html
            --coverage-text

    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/phpunit.clover.xml
        reports:
            junit: development/build/artifacts/phpunit.junit.xml
